const products = [
  {
    _id: "1",
    name: "Warrior Alpha DX Grip Senior Hockey Stick",
    image: "/images/WarriorStick.jpg",
    description:
      "Brand new for the 2019-2020 season is the Warrior Alpha DX Senior Hockey Stick from Warrior Hockey. This second iteration of the Alpha stick line features upgrades made to both the shaft as well as the blade making the Alpha DX Hockey Stick one of Warrior’s most advanced to date!",
    brand: "Warrior",
    category: "Sticks",
    price: 259.99,
    countInStock: 10,
    rating: 4.0,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Bauer Vapor 2x Pro Senior Ice Hockey Skates",
    image: "/images/BauerSkates.jpg",
    description:
      "Bauer Hockey is proud to unveil their latest addition to their Vapor skate line with the introduction of the Bauer Vapor 2X Pro Senior Ice Hockey Skates! With key improvements made to nearly every part of the skates, Bauer looks to offer ultimate performance every time you step onto the ice!",
    brand: "Bauer",
    category: "Skates",
    price: 759.99,
    countInStock: 7,
    rating: 4.5,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "CCM 50 Senior Hockey Helmet Combo",
    image: "/images/CCMHelmet.jpg",
    description:
      "Adjustment: Easy tool free adjustment on the side of the helmet for a custom fit, Liner: New Liner designed to provide high level of protection and comfort, Shell: Lightweight but high density PE shell construction, Wires: Thin Round wires to provide maximum line of sight, & Chin Cup: Comfort foam with a wire guard",
    brand: "CCM",
    category: "Helmets",
    price: 64.99,
    countInStock: 5,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "SherWood Rekker M80 Senior Hockey Gloves",
    image: "/images/SherwoodGloves.jpg",
    description:
      "Built with cable knit nylon throughout, the Rekker M80 Hockey Gloves are highly durable and resistant to cutting-type impacts! Furthermore, these gloves utilize an anatomical, close to the hand fit, providing players with optimal protection, comfort, and feel.",
    brand: "SherWood",
    category: "Gloves",
    price: 119.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Warrior Pro Player Medium 28in. Hockey Equipment Bag",
    image: "/images/WarriorBag.jpg",
    description:
      "Pro locker room size and specifications used by pro teams, large durable main compartment, internal mesh skate pockets, and fully customizable. Dimensions are 28in X 15in X 15in.",
    brand: "Warrior",
    category: "Bags",
    price: 79.99,
    countInStock: 7,
    rating: 3,
    numReviews: 10,
  },
  {
    _id: "6",
    name: "Bauer Standard Ice Hockey Puck",
    image: "/images/BauerPuck.jpg",
    description: "Bauer's standard ice hockey puck.",
    brand: "Bauer",
    category: "Pucks",
    price: 1.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
];

export default products;
